package editor.editionData;

public sealed interface EditionData permits AnimationEditionData, CompositeHitboxEditionData, DisplaySpawnInfoEditionData, EntitySpawnInfoEditionData, FixedTrajectoryEditionData, PlayerControlledTrajectoryEditionData, ProjectileEditionData, ScrollingImageEditionData, ShipEditionData, ShotEditionData, SimpleRectangleHitboxEditionData {

}
